# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46281782758fbb54f2fc41c335feec63d7bd81fe31532f3180f18b0f007075525d9a8f81d30e3cbad0fd10bab93ee815c5f4c264032d19bc870eb894145dabfc

test:
  secret_key_base: 046680a5e1181fb3fd303eb021b6358b3c1599e69df2244ec3c4dc58b4197fb9a1ee2b6dae834a48e6659ccbf6569435da3fb3aa97dfb06bdd60fbfa61139424

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
